Ревью
While-true-Technopark/BaumanRacing pull request #1
Opened 2019-12-24 12:33 UTC by Slava-Romanov

2019-12-25 17:39 UTC, sanya554455 commented on client/linters/cppcheck/cfg/bsd.cfg
> +      <not-uninit/>
sfg файлы и прочее засуньте в gitignore

2019-12-25 17:39 UTC, sanya554455 commented on server/source/game_manager/game_manager.cpp
> +const int8_t NUM_CIRCLE = 1;
Лучше засунуть в поля класса, глобальные переменные это не очень

2019-12-25 17:39 UTC, sanya554455 commented on server/source/game_manager/game_manager.cpp
> +    for (size_t idx = 0; idx < num_players; ++idx) {
idx название переменной ни о чем не говорит

2019-12-25 17:39 UTC, sanya554455 commented on server/source/game_manager/map.cpp
> +    start_pos = {3830, 7320, 0}; // TODO: из файла (Рома)
Магические числа

2019-12-25 17:39 UTC, sanya554455 commented on server/source/game_manager/map.cpp
> +    double x_beg = start_pos[0] - 30;
Магические числа

2019-12-25 17:39 UTC, sanya554455 commented on server/source/start_server.cpp
> +const std::string MAIN = "print 'info' or 'stop'";
в переменную класса

2019-12-25 17:39 UTC, sanya554455 commented on server/source/test_client.cpp
> +                std::cout << "send on ping" << std::endl; // TODO: logger
в логгер

2019-12-25 17:39 UTC, sanya554455 commented on transfer_lib/config/config.hpp
> +const size_t DOF = DIM + 1;  // x, y, angle
непонятно что за переменные и числа

2019-12-25 17:39 UTC, sanya554455 commented on transfer_lib/transfer/message.hpp
> +    static const std::string settings;
переменных слишком много, может лучше разнести по классам со своей ответственностью, или однажды засунуть все в вектор, и потом делать проход по вектору чем switch case

2019-12-25 17:39 UTC, sanya554455 commented on transfer_lib/transfer/command.hpp
> +    bool back;
вектор moves

2019-12-25 17:39 UTC, sanya554455 commented on server/source/test_client.cpp
> +        // clt.setBlocking(false);
ненужные комментарии

2019-12-25 17:39 UTC, sanya554455 commented on server/source/server/server.cpp
> +    for (const std::string& room_name: del_rooms) {
auto

2019-12-25 17:39 UTC, sanya554455 commented on server/source/server/server.cpp
> +    for (size_t idx = 0; idx < guests.size(); ++idx) {
for( auto &idx : guests)

2019-12-25 17:39 UTC, sanya554455 commented on transfer_lib/transfer/message.cpp
> +const std::string message::room_name = "room_name";
vector из всех message

2019-12-25 17:40 UTC, sanya554455 commented
В целом, много параметров захардкожены - не расширяемо. Ну и много переменных разбросано по классу, лучше хранить их в контейнере

2019-12-25 19:00 UTC, alexey-ershkov requested changes

2019-12-25 19:00 UTC, alexey-ershkov commented on client/source/Event/event.hpp
> +enum event_type {
Нерасширяемые event-ы, при росте игры придется много хардкодить, что может привести к усложнению и затягиванию разработки

2019-12-25 19:00 UTC, alexey-ershkov commented on client/source/Event/event.hpp
> +union event_data {
Union - ненадежная конструкция,  лучше использовать std::variant

2019-12-25 19:00 UTC, alexey-ershkov commented on client/source/Application/application.cpp
> +        switch (e_input.type) {
Огромный switch-case, напрашивается паттерн "Цепочка обязанностей". Плюс позволит сделать набор событий расширяемым

2019-12-25 19:00 UTC, alexey-ershkov commented on client/source/Input/input.cpp
> +                   //std::cout << "ASCII character typed: " << static_cast<char>(event.text.unicode) << std::endl;
Не лучшая практика  - оставлять отладочные печати

2019-12-25 19:00 UTC, alexey-ershkov commented on client/source/Input/input.cpp
> +void input::start_control() {
Зачем пустые функции?

2019-12-25 19:00 UTC, alexey-ershkov commented on client/source/Input/input.hpp
> +    struct keys_pressed_variants get_pressed_keys();
Было бы здорово писать override у переопределяемых визуальных методов - повышает читабельность кода. Не нужно идти в интерфейсный класс

2019-12-25 19:00 UTC, alexey-ershkov commented on client/source/Input/input_manager.cpp
> +    switch (e.type) {
Конструкция if-else была бы более уместна здесь

2019-12-25 19:00 UTC, alexey-ershkov commented on client/source/Input/input_manager.cpp
> +    if (keys.closing == true) {
А вот здесь наоборот switch-case просится

2019-12-25 19:00 UTC, alexey-ershkov commented on client/source/Input/input_abst.hpp
> +
Красивая идея с реализацей абстракного класса ввода)

2019-12-25 19:00 UTC, alexey-ershkov commented on client/source/Loader/loader_manager.hpp
> +#define LDR_MNGR_OK 0
Здесь проще использовать enum - не задействуем препроцессор и защищаем от ошибок макроопределений

2019-12-25 19:00 UTC, alexey-ershkov commented on client/source/Network/network_manager.cpp
> +        if (msg[message::head] == message::ping && msg[message::body] == message::to) {
Просится сюда switch-case

2019-12-25 19:00 UTC, alexey-ershkov commented on client/source/Network/network_manager.cpp
> +int network_manager::handle_event(const event & e) {
Нерасширяеемый набор событий

2019-12-25 19:00 UTC, alexey-ershkov commented on client/source/Renderer/renderer_abst.hpp
> +#define STR256 "
Магическая константа

2019-12-25 19:00 UTC, alexey-ershkov commented on client/source/Renderer/renderer_abst.hpp
> +class renderer_abst {
На мой взгляд слишком большой объект, проще разделить на несколько маленьких, по логике отображаемого.

2019-12-25 19:00 UTC, alexey-ershkov commented on client/source/Renderer/renderer_manager.cpp
> +    switch (e.type) {
Снова просится паттерн "Цепочка обязанностей"

2019-12-26 22:18 UTC, Davt2000 requested changes

2019-12-26 22:18 UTC, Davt2000 commented on client/source/Application/application.cpp
> +                break;
Идентичный код, срабатывающий в разных случаях кейса. Или недописано(на что намекают //TODO), либо просто лишний код, который можно убрать

2019-12-26 22:18 UTC, Davt2000 commented on client/source/Renderer/renderer.cpp
> +    background.setPosition(-2000,-2000);
Огромное множество магических чисел

2019-12-27 12:45 UTC, Slava-Romanov commented on client/source/Event/event.hpp
> +enum event_type {
Почему не расширяемые? Мы просто добавляем внизу новый тип и, если ему необходимо, новую структуру передачи данных

2019-12-27 12:46 UTC, Slava-Romanov commented on client/source/Input/input.cpp
> +void input::start_control() {
Изначально она планировались для использования, будут удалены

2019-12-27 12:46 UTC, Slava-Romanov commented on client/source/Network/network_manager.cpp
> +        if (msg[message::head] == message::ping && msg[message::body] == message::to) {
У нас при одном типе может быть разная структура body

2019-12-27 12:47 UTC, Slava-Romanov commented on client/source/Renderer/renderer_abst.hpp
> +#define STR256 "
Да, отчасти это костыль, чтобы заполнить всю строку пробелами

2019-12-27 12:48 UTC, Slava-Romanov commented on client/source/Application/application.cpp
> +                break;
Да, это недописано в текущей ветке

2019-12-27 12:53 UTC, Slava-Romanov commented on client/source/Event/event.hpp
> +union event_data {
Согласен

2019-12-27 12:53 UTC, Slava-Romanov commented on client/source/Input/input.cpp
> +                   //std::cout << "ASCII character typed: " << static_cast<char>(event.text.unicode) << std::endl;
Да, иногда их расскомментируем для дополнительной отладки

2019-12-27 12:54 UTC, Slava-Romanov commented on client/source/Network/network_manager.cpp
> +int network_manager::handle_event(const event & e) {
Почему нерасширяемый?  Просто добавляем новый блок if

2019-12-27 12:55 UTC, Slava-Romanov commented on server/source/server/server.cpp
> +    for (size_t idx = 0; idx < guests.size(); ++idx) {
Согласен, можно так упростить

2020-02-05 18:05 UTC, merged